post:
  tags:
    - Users API
  summary: Update user settings
  description: To update user settings, post to the following with properties that need to be updated. Properties that should not be updated must be omitted.
  operationId:
  requestBody:
    content:
      application/json:
        schema:
          $ref:
  responses:
    200:
      description: OK.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "/src/swagger.yaml#/components/schemas/ProfileSettings"
          examples:
            schedule:
              value:
                 appAlerts: yes
                 emailAlerts: yes
                 cujoEmailUpdates: yes
                 cujoStatusLights: yes
                 pinCode: yes
                 flowData: yes
